sudo: required
services:
  - docker

before_install:
  - docker pull gcr.io/cpp-projects/cpp-ci:1

script:
  - >
    docker run -v `pwd`:/leatherman gcr.io/cpp-projects/cpp-ci:1 /bin/bash -c "
    cd /leatherman &&
    rm locales/leatherman.pot &&
    cmake $EXTRA_VARS . &&
    mkdir dest &&
    make $TARGET DESTDIR=/leatherman/dest -j2 &&
    { [ '$COVERALLS' == 'ON' ] && coveralls --gcov-options '\-lp' -r . -b . -e src -e vendor >/dev/null || true; }
    "
  - if [ "$DO_RELEASE" == "true" ]; then tar czvf leatherman.tar.gz `find dest -type f -print`; fi

env:
  matrix:
    - TARGET=cpplint
    - TARGET=cppcheck
    - TARGET="all test install ARGS=-v" DO_RELEASE=true EXTRA_VARS="-DBOOST_STATIC=ON"
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON" COVERALLS=ON
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DLEATHERMAN_SHARED=ON"
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DLEATHERMAN_USE_LOCALES=OFF"
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DLEATHERMAN_GETTEXT=OFF"

deploy:
  provider: releases
  api_key:
    secure: XARXGAo5DNbqu7/EVPlKocdAAdtVqui2yaJiqw8GVXMSsK5lxqkHNfm1UF204y9ONl7DTa1hzBS8VRLupfb2aIjIZWMM68tnWYbyJYNdRUevylPTK01rO9wpR8iVe7xFqQOlDXPrX0UVfKCvf+e1j+IleO5Eyjf1mTLIRR3fuOY=
  file: leatherman.tar.gz
  skip_cleanup: true
  on:
    repo: puppetlabs/leatherman
    tags: true
    condition: '"$DO_RELEASE" == "true"'
