clone_depth: 10
install:
  - set
  - git submodule update --init --recursive

  - choco install -y mingw-w64 -Version 4.8.3 -source https://www.myget.org/F/puppetlabs
  - choco install -y cmake -Version 3.2.2 -source https://www.myget.org/F/puppetlabs
  - ps: wget 'https://s3.amazonaws.com/kylo-pl-bucket/gettext-tools-static-0.18.1.1.zip' -OutFile "$pwd\gettext.zip"
  - ps: 7z.exe x gettext.zip -oC:\tools | FIND /V "ing  "
  - SET PATH=C:\Ruby21-x64\bin;C:\tools\mingw64\bin;C:\tools\gettext-tools-static-0.18.1.1;%PATH%
  - ps: $env:PATH = $env:PATH.Replace("Git\bin", "Git\cmd")
  - ps: $env:PATH = $env:PATH.Replace("Git\usr\bin", "Git\cmd")

  - ps: wget 'https://s3.amazonaws.com/kylo-pl-bucket/boost_1_57_0-x86_64_mingw-w64_4.8.3_win32_seh.7z' -OutFile "$pwd\boost.7z"
  - ps: 7z.exe x boost.7z -oC:\tools | FIND /V "ing  "

  - ps: wget 'https://s3.amazonaws.com/kylo-pl-bucket/curl-7.42.1-x86_64_mingw-w64_4.8.3_win32_seh.7z' -OutFile "$pwd\curl-7.42.1-x86_64_mingw-w64_4.8.3_win32_seh.7z"
  - ps: 7z.exe x "curl-7.42.1-x86_64_mingw-w64_4.8.3_win32_seh.7z" -oC:\tools | FIND /V "ing "

build_script:
  - ps: cmake -G "MinGW Makefiles" -DBOOST_ROOT="C:\tools\boost_1_57_0-x86_64_mingw-w64_4.8.3_win32_seh" -DCMAKE_PREFIX_PATH="C:\tools\curl-7.42.1-x86_64_mingw-w64_4.8.3_win32_seh" -DCMAKE_INSTALL_PREFIX=C:\tools\leatherman -DCURL_STATIC=ON -DLEATHERMAN_SHARED="$env:shared" .
  - ps: mingw32-make install
  - ps: 7z.exe a -t7z leatherman.7z C:\tools\leatherman\

test_script:
  - ps: if ($env:shared -eq "OFF") { ctest -V 2>&1 | %{ if ($_ -is [System.Management.Automation.ErrorRecord]) { $_ | c++filt } else { $_ } } }

environment:
  matrix:
  - shared: OFF
  - shared: ON

artifacts:
  - path: leatherman.7z
    name: leatherman.7z

deploy:
  description: Leatherman build from AppVeyor
  provider: GitHub
  auth_token:
    secure: pSPKogvXGsTpt4hZPOWEMPpiwcYCKpTuQODqmsdN34Av6nN640H0DPiK/sKwDhMP
  artifact: leatherman.7z
  on:
    appveyor_repo_tag: true
    shared: OFF
